
language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: false
#    - os: osx
#      compiler: clang

addons:
  apt:
    packages:
      - autopoint
      - intltool
      # DRM
      - libdrm-dev
      # RANDR
      - libxcb1-dev
      - libxcb-randr0-dev
      # VidMode
      - libx11-dev
      - libxxf86vm-dev
      # GeoClue2
      - libglib2.0-dev
      # GUI
      - python3

install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew install gettext
    brew install intltool
  fi

script: |
  ./bootstrap && ./configure --enable-drm --enable-vidmode --enable-randr --enable-geoclue2 --enable-gui && make -j2 distcheck
